# Generated by Django 5.0.4 on 2024-04-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puzzles',
            new_name='Puzzle',
        ),
        migrations.RenameModel(
            old_name='PuzzleTypes',
            new_name='PuzzleType',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
