# Generated by Django 5.0.4 on 2024-04-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleview', '0003_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='rules',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PuzzleSetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzleview.puzzle')),
                ('setter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzleview.setter')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='setter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzleview.setter'),
        ),
    ]
