# Generated by Django 5.0.4 on 2024-04-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleview', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='name',
            new_name='title',
        ),
    ]
